name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build container
      run: docker-compose build
    - name: Show image info
      run: docker images
    - name: Test container
      run: docker-compose run -w /app main pandoc -t html5 < README.md > readme.html
    - uses: actions/upload-artifact@v1
      with:
        name: readme.html
        path: readme.html
